rename and update dependency
bluehalo/node-fhir-server-mongo pull request #153
Opened 2024-08-28 21:07 UTC by ekdeveloper

2024-09-11 15:26 UTC, ekdeveloper commented on Dockerfile
> +    # yarn config set registry http://host.docker.internal:4873; \
add option for testing with private repo

2024-09-11 15:27 UTC, ekdeveloper commented on src/config.js
> -  options: {
depreciated

2024-09-11 15:28 UTC, ekdeveloper commented on src/services/allergyintolerance/allergyintolerance.service.js
> +    collection.findOne({ id: id.toString() })
fix call w/ mongo driver

2024-09-11 15:43 UTC, otchet-broad requested changes
There's an entire school of thought about returning error messages from an external system.  See https://csf.tools/reference/nist-sp-800-53/r5/si/si-11/

I think it's worth updating the pattern with mongo to return a controlled message instead of the raw error from MongoDB.

2024-09-11 15:55 UTC, otchetbluehalo requested changes
There's an entire school of thought about returning error messages from an external system.  See https://csf.tools/reference/nist-sp-800-53/r5/si/si-11/

I think it's worth updating the pattern with mongo to return a controlled message instead of the raw error from MongoDB.

2024-09-11 15:58 UTC, ekdeveloper commented
> There's an entire school of thought about returning error messages from an external system. See https://csf.tools/reference/nist-sp-800-53/r5/si/si-11/
> 
> I think it's worth updating the pattern with mongo to return a controlled message instead of the raw error from MongoDB.

I'll make another ticket for that.  I believe it is beyond the scope of this PR

2024-09-11 16:10 UTC, ekdeveloper commented
Merge this pr after issue https://github.com/bluehalo/node-fhir-server-mongo/issues/157 is merge into this PR

2024-09-13 14:44 UTC, ekdeveloper commented on src/services/patient/patient.service.js
> +              created: res && res.lastErrorObject ? !res.lastErrorObject.updatedExisting : false,
this was updated to support null check and default to false.  This was a bug previously where the first put would fail

2024-09-13 14:46 UTC, ekdeveloper commented on .github/workflows/lint.yml
> -  run-tests:
no need for dind for just lint

2024-09-13 14:50 UTC, otchetbluehalo submitted a review, later dismissed
Thanks for improving coverage and getting the error handling updated.

2024-09-13 14:54 UTC, otchetbluehalo approved these changes

2024-09-13 14:55 UTC, merged